[package]
name = "Apis_With_Axum"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.4" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
csv = "1.3"