[package]
name = "Into_To_Axum"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio ={ version = "1", features = ["full"] }
axum ={ version = "0.8" }
serde ={ version = "*", features = ["derive"] }
serde_json = { version = "*" }